apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-demo-app1-deployment
spec:
  selector:
    matchLabels:
      app: some-demo-app1
  replicas: 3
  template:
    metadata:
      labels:
        app: some-demo-app1
    spec:
      containers:
      - name: some-demo-app1
        image: localhost:5000/some-demo-app1:0.0.4-SNAPSHOT
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: minikube
